In [1]:
import torch

data = [[1,2,3],[4,5,6]]

In [2]:
my_tensor = torch.tensor(data)

print(my_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [5]:
shape = (2,3)

ones = torch.ones(shape)
zeros = torch.zeros(shape)
random = torch.randn(shape)

print(f"ones Tensor:\n {ones}")
print(f"zeros Tensor:\n {zeros}")
print(f"Random Tensor:\n {random}")

ones Tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
zeros Tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Random Tensor:
 tensor([[ 1.6671, -1.9707,  0.7999],
        [ 1.4807,  0.2400,  0.6347]])


In [6]:
template = torch.tensor([[1,2],[3,4]])

In [7]:
rand_like = torch.randn_like(template, dtype=float)

In [8]:
print(f"Template tensor:\n {template}")
print(f"Rand_like tensor:\n {rand_like}")

Template tensor:
 tensor([[1, 2],
        [3, 4]])
Rand_like tensor:
 tensor([[ 0.2598,  1.4612],
        [ 1.0156, -0.0946]], dtype=torch.float64)


In [9]:
tensor = torch.randn(2,3)

In [11]:
print(f"Shape: {tensor.shape}")
print(f"Datatype: {tensor.dtype}")
print(f"Device: {tensor.device}")

Shape: torch.Size([2, 3])
Datatype: torch.float32
Device: cpu


In [13]:
x_data = torch.tensor([[1,2],[3,4]],dtype=float)
w = torch.tensor([[1.0],[2.0]], requires_grad=True)

In [14]:
print(f"Data tensor requires_grad: {x_data.requires_grad}")
print(f"param tensor requires_grad: {w.requires_grad}")

Data tensor requires_grad: False
param tensor requires_grad: True


In [15]:
a = torch.tensor(2.0,requires_grad=True)
b = torch.tensor(3.0,requires_grad=True)
x = torch.tensor(4.0,requires_grad=True)

In [16]:
y = a + b
z = x * y

In [17]:
print(f"result z: {z}")

result z: 20.0


In [18]:
print(f"grad_fn for z: {z.grad_fn}")
print(f"grad_fn for y: {y.grad_fn}")
print(f"grad_fn for a: {a.grad_fn}")


grad_fn for z: <MulBackward0 object at 0x000001F345F9FE50>
grad_fn for y: <AddBackward0 object at 0x000001F3556FE110>
grad_fn for a: None


In [19]:
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[10,20],[30,40]])

element_wise_product = a * b

In [20]:
print(element_wise_product)

tensor([[ 10,  40],
        [ 90, 160]])


In [21]:
m1 = torch.tensor([[1,2,3],[4,5,6]]) #shape-2,3
m2 = torch.tensor([[7,8],[9,10],[11,12]]) #shape-3,2

matrix_product1 = m1 @ m2 #expt shape-2,2
matrix_product2 = m2 @ m1 #expt shape-3,3

In [22]:
print(matrix_product1)
print(matrix_product2)

tensor([[ 58,  64],
        [139, 154]])
tensor([[ 39,  54,  69],
        [ 49,  68,  87],
        [ 59,  82, 105]])


In [23]:
scores = torch.tensor([[10,20,30],[5,10,15]],dtype=float)
average_score = scores.mean()
print(f"Overall mean: {average_score}")

Overall mean: 15.0


In [24]:
avg_per_assignment = scores.mean(dim=0)
avg_per_student = scores.mean(dim=1)

print(avg_per_assignment)
print(avg_per_student)

tensor([ 7.5000, 15.0000, 22.5000], dtype=torch.float64)
tensor([20., 10.], dtype=torch.float64)


In [25]:
x = torch.arange(12).reshape(3,4)

col_2 = x[:,2]

In [26]:
print(x)
print(col_2)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([ 2,  6, 10])


In [27]:
scores = torch.tensor([[10,0,5,20,1],[1,30,2,5,0]])

best_indices = torch.argmax(scores, dim=1)

In [28]:
best_indices

tensor([3, 1])

In [29]:
best_scores = torch.max(scores,dim=1)

In [30]:
best_scores

torch.return_types.max(
values=tensor([20, 30]),
indices=tensor([3, 1]))

In [31]:
best_scores.values

tensor([20, 30])

In [32]:
best_scores.indices

tensor([3, 1])

In [33]:
data = torch.tensor([
    [10,11,12,13],
    [20,21,22,23],
    [30,31,32,33]
])

indices_to_select = torch.tensor([[1],[2],[3]])

selected_values = torch.gather(data, dim=1, index=indices_to_select)

In [35]:
print(selected_values)

tensor([[11],
        [22],
        [33]])


In [36]:
N = 10

D_in = 1
D_out = 1

X = torch.randn(N,D_in)

true_W = torch.tensor([[2.0]])
true_b = torch.tensor(1.0)

y_true = X @ true_W + true_b + torch.randn(N,D_out) * 0.1

In [38]:
print(y_true)

tensor([[-0.8051],
        [-0.2283],
        [ 0.2522],
        [ 0.9755],
        [-4.8780],
        [ 0.2158],
        [ 0.8999],
        [ 3.1749],
        [ 1.2765],
        [ 3.1431]])


In [40]:
W = torch.randn(D_in,D_out,requires_grad=True)
b = torch.randn(1,requires_grad=True)

print(f"initial weight: \n {W} \n")
print(f"initial bias:\n {b}")

initial weight: 
 tensor([[0.3067]], requires_grad=True) 

initial bias:
 tensor([0.4059], requires_grad=True)


In [44]:
y_hat = X @ W + b

In [45]:
print(y_hat)
print(y_true)

tensor([[ 0.1094],
        [ 0.2457],
        [ 0.3073],
        [ 0.4013],
        [-0.4888],
        [ 0.2805],
        [ 0.3953],
        [ 0.7379],
        [ 0.4626],
        [ 0.7513]], grad_fn=<AddBackward0>)
tensor([[-0.8051],
        [-0.2283],
        [ 0.2522],
        [ 0.9755],
        [-4.8780],
        [ 0.2158],
        [ 0.8999],
        [ 3.1749],
        [ 1.2765],
        [ 3.1431]])


In [46]:
error = y_hat - y_true
squared_error = error ** 2
loss = squared_error.mean()

print(f"loss: {loss}")


loss: 3.323979616165161


In [47]:
loss.backward()

print(f"grad for W: {W.grad}")
print(f"grad for b: {b.grad}")

grad for W: tensor([[-3.8873]])
grad for b: tensor([-0.1648])


In [49]:
learning_rate, epochs = 0.1, 100

W, b = torch.randn(1,1,requires_grad=True), torch.randn(1,requires_grad=True)

for epoch in range(epochs):
    y_hat = X @ W + b
    loss = torch.mean((y_hat - y_true)**2)

    loss.backward()

    with torch.no_grad():
        W -= learning_rate * W.grad
        b -= learning_rate * b.grad

    W.grad.zero_(), b.grad.zero_()

    if epoch % 10 == 0:
        print(f"Epoch {epoch:02d}: Loss {loss.item():.4f}, W={W.item():.3f}, b={b.item():.3f}")

print(f"\n Final params: W={W.item():.3f}, b={b.item():.3f}")

Epoch 00: Loss 6.3952, W=0.228, b=-0.226
Epoch 10: Loss 0.1346, W=1.787, b=0.699
Epoch 20: Loss 0.0105, W=1.959, b=0.913
Epoch 30: Loss 0.0071, W=1.985, b=0.950
Epoch 40: Loss 0.0070, W=1.989, b=0.957
Epoch 50: Loss 0.0070, W=1.990, b=0.958
Epoch 60: Loss 0.0070, W=1.990, b=0.958
Epoch 70: Loss 0.0070, W=1.990, b=0.958
Epoch 80: Loss 0.0070, W=1.990, b=0.958
Epoch 90: Loss 0.0070, W=1.990, b=0.958

 Final params: W=1.990, b=0.958


In [50]:
D_in = 1
D_out = 1

linear_layer = torch.nn.Linear(in_features=D_in, out_features=D_out)

print(f"Layer weight (W): {linear_layer.weight}")
print(f"Layer bias (b): {linear_layer.bias}")

y_hat_nn = linear_layer(X)

print(f"Output of nn.Linear (first 3 rows): \n {y_hat_nn[:3]}")

Layer weight (W): Parameter containing:
tensor([[0.1752]], requires_grad=True)
Layer bias (b): Parameter containing:
tensor([-0.4774], requires_grad=True)
Output of nn.Linear (first 3 rows): 
 tensor([[-0.6468],
        [-0.5689],
        [-0.5337]], grad_fn=<SliceBackward0>)


In [51]:
relu = torch.nn.ReLU()
sample_data = torch.tensor([-2.0,-0.5,0.0,0.5,2.0])
activated_data = relu(sample_data)

In [52]:
print(f"original data: {sample_data}")
print(f"data after relu: {activated_data}")

original data: tensor([-2.0000, -0.5000,  0.0000,  0.5000,  2.0000])
data after relu: tensor([0.0000, 0.0000, 0.0000, 0.5000, 2.0000])


In [54]:
softmax = torch.nn.Softmax(dim=-1)
logits = torch.tensor([[1.0,3.0,0.5,1.5],[-1.0,2.0,1.0,0.0]])
probabilites = softmax(logits)

In [55]:
probabilites

tensor([[0.0939, 0.6942, 0.0570, 0.1549],
        [0.0321, 0.6439, 0.2369, 0.0871]])

In [61]:
probabilites[1].sum().dtype

torch.float32

In [62]:
vocab_size = 10
embedding_dim = 3

embedding_layer =  torch.nn.Embedding(vocab_size, embedding_dim)

input_ids = torch.tensor([[1,5,0,8]])
word_vectors = embedding_layer(input_ids)

In [63]:
word_vectors

tensor([[[-0.2855, -0.3040,  2.5985],
         [-0.5740, -0.5498,  0.6177],
         [ 0.3321, -0.6037,  1.1036],
         [-0.1527,  0.4685, -1.4403]]], grad_fn=<EmbeddingBackward0>)

In [65]:
norm_layer = torch.nn.LayerNorm(normalized_shape=3)
input_features = torch.tensor([[[1,2,3],[4,5,6]]],dtype=torch.float32)
normalized_features = norm_layer(input_features)

In [66]:
normalized_features

tensor([[[-1.2247,  0.0000,  1.2247],
         [-1.2247,  0.0000,  1.2247]]], grad_fn=<NativeLayerNormBackward0>)

In [67]:
dropout_layer = torch.nn.Dropout(p=0.5)
input_tensor = torch.ones(1,10)

dropout_layer.train()
output_during_training = dropout_layer(input_tensor)

dropout_layer.eval()
output_during_eval = dropout_layer(input_tensor)

In [69]:
print(output_during_training)
print(output_during_eval)

tensor([[2., 0., 2., 2., 2., 2., 0., 2., 0., 2.]])
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


In [71]:
import torch.nn as nn

class LinearRegressionModel(nn.Module):
    def __init__(self,in_features,out_features):
        super().__init__()
        self.linear_layer = nn.Linear(in_features, out_features)

    def forward(self, x):
        return self.linear_layer(x)

model = LinearRegressionModel(in_features=1,out_features=1)



In [72]:
print("model architecture")
print(model)

model architecture
LinearRegressionModel(
  (linear_layer): Linear(in_features=1, out_features=1, bias=True)
)


In [73]:
import torch.optim as optim

learning_rate = 0.01

optimizer = optim.Adam(model.parameters(), lr=learning_rate)

loss_fn = nn.MSELoss()

In [75]:
epochs = 100

for epoch in range(epochs):
    y_hat = model(X)
    loss = loss_fn(y_hat, y_true)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    if epoch % 10 == 0:
        print(f"Epoch {epoch:02d}: loss = {loss.item():.4f}")


Epoch 00: loss = 3.4407
Epoch 10: loss = 2.9839
Epoch 20: loss = 2.5896
Epoch 30: loss = 2.2539
Epoch 40: loss = 1.9639
Epoch 50: loss = 1.7064
Epoch 60: loss = 1.4745
Epoch 70: loss = 1.2668
Epoch 80: loss = 1.0825
Epoch 90: loss = 0.9201
