In [10]:
from importlib import reload
import src.datasets

reload(src.datasets)

<module 'src.datasets' from 'C:\\Users\\dwhip\\PycharmProjects\\chromatintune\\src\\datasets.py'>

In [3]:
from src.utils import one_hot_encode

x = one_hot_encode("ACGTACGT")

print(x.shape)
print(x)

(8, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
from src.datasets import SequenceDataset

dataset = SequenceDataset(
    "../data/raw/mock_data.csv"
)

print(len(dataset))

x, y = dataset[0]

print(x.shape)
print(y)

4
torch.Size([4, 10])
tensor(0.8200)


In [12]:
from src.model import SequenceCNN

model = SequenceCNN()

x = x.unsqueeze(0)

print(x.shape)

output = model(x)

print(output)

torch.Size([1, 4, 10])
tensor([[0.1331]], grad_fn=<AddmmBackward0>)


In [13]:
from torch.utils.data import DataLoader

dataloader = DataLoader(
    dataset,
    batch_size=2,
    shuffle=True
)

In [14]:
for batch_x, batch_y in dataloader:

    print(batch_x.shape)
    print(batch_y.shape)

    break

torch.Size([2, 4, 10])
torch.Size([2])
